Resolve compiler_flags to allow Mac build (#3478)
Summary:
Pull Request resolved: https://github.com/pytorch/executorch/pull/3478

## `-Wglobal-constructors`

In ET-Vulkan, we use global constructors without global destructors.

Example: [`auto cls = VulkanBackend();`](https://github.com/pytorch/executorch/blob/3a253e96baa89e5a5434e91a236df63d54e0949e/backends/vulkan/runtime/VulkanBackend.cpp#L511-L513)
```
xplat/executorch/backends/vulkan/runtime/VulkanBackend.cpp:511:6: error: declaration requires a global destructor [-Werror,-Wglobal-constructors]
auto cls = VulkanBackend();
     ^
```

On Mac, this results in a `-Wglobal-constructors` warning, which is disabled in this change.

## `-Wmissing-prototypes`
## `-Wshadow`

Same as https://github.com/pytorch/pytorch/pull/125361

Differential Revision: D56860764