Revert "Use std::optional" (#15612)
Reverts pytorch/executorch#12707

This causes 1000s of internal CI failures, e.g.,

error: no template named 'optional' in namespace 'torch::executor'; did
you mean simply 'optional'?
using optional = torch::executor::optional<T>;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~
                 optional
note: 'optional' declared here
using ::executorch::aten::optional;