Fix doc build GLIBCXX_3.4.30 not found (#2376)
Summary:
The hack is from https://github.com/pytorch/pytorch/pull/121547.  This is to fix the failing doc build on 22.04, i.e. https://github.com/pytorch/executorch/actions/runs/8167685547/job/22328481328

```
ImportError: /opt/conda/envs/py_3.10/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
```

Pull Request resolved: https://github.com/pytorch/executorch/pull/2376

Reviewed By: guangy10

Differential Revision: D54818139

Pulled By: huydhn

fbshipit-source-id: aad8408908ef52f15a32395c31cc1698cd337c6b