Fix script export_hf_model.py (#6246)
Summary:
Having `bos_token_id = None` (and other fields) will cause an emitter error for models that doesn't define that field, for example, [olmo-1b](https://huggingface.co/allenai/OLMo-1B-hf/blob/main/config.json#L8).
```
    raise ExportError(
executorch.exir.error.ExportError: [ExportErrorType.NOT_SUPPORTED]: Error emitting get_bos_id which returns a value of type <class 'NoneType'>. which is not a supported primitive
```

This PR avoids emitting with unsupported primitive type by removing the `None` fields out from the model metadata. The ExecuTorch runtime will assume the default value for those unspecified fields.

Pull Request resolved: https://github.com/pytorch/executorch/pull/6246

Reviewed By: kirklandsign

Differential Revision: D64438406

Pulled By: guangy10

fbshipit-source-id: dceb7a08c1231d7dadf237476b9a229580a96b94