Executorch ops fail to build on macbook M1 due to bad formatting
Summary:
```
....
executorch/kernels/quantized/cpu/embeddingxb.cpp:140:11: error: format specifies type 'char' but the argument has type 'int32_t' (aka 'int') [-Werror,-Wformat]
          i,
          ^~
executorch/runtime/platform/assert.h:39:59: note: expanded from macro 'ET_CHECK_MSG'
      ET_ASSERT_MESSAGE_EMIT(" (%s): " _format, #_cond, ##__VA_ARGS__); \
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
executorch/runtime/platform/assert.h:26:9: note: expanded from macro 'ET_ASSERT_MESSAGE_EMIT'
      ##__VA_ARGS__)
      ~~^~~~~~~~~~~~
executorch/runtime/platform/log.h:172:13: note: expanded from macro 'ET_LOG'
          ##__VA_ARGS__);                                            \
            ^~~~~~~~~~~
1 warning and 1 error generated.
```

Reviewed By: dongpujin, manuelcandales

Differential Revision: D65156573