pte mode: Add error message and instruction for full logits. (#5031)
Summary:
A llama pte file is exported with the last logits only to save memory. However, eval_llama requires full logits. Check the logits dim and raise meaningful error, with instructions on how to export a .pte file with full logits.


Test Plan:
```
% python -m examples.models.llama2.eval_llama --pte /Users/myuan/data/Llama3_2/1B/int4g128e8g256_2048.pte -t /Users/myuan/data/Llama3_2/1B/tokenizer.model --max_seq_len 2048 --limit 1000
/Users/myuan/miniconda3/envs/executorch/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
/Users/myuan/miniconda3/envs/executorch/lib/python3.10/site-packages/transformers/data/metrics/__init__.py:19: UserWarning: A NumPy version >=1.23.5 and <2.3.0 is required for this version of SciPy (detected version 1.21.3)
  from scipy.stats import pearsonr, spearmanr
Using Tiktokenizer
2024-09-02:18:12:45,091 INFO     [tiktoken.py:88] Reloaded SentencePiece model from /Users/myuan/data/Llama3_2/1B/tokenizer.model
2024-09-02:18:12:45,091 INFO     [tiktoken.py:99] #words: 128256 - BOS ID: 128000 - EOS ID: 128001
2024-09-02:18:12:45,104 INFO     [huggingface.py:162] Using device 'cpu'
2024-09-02:18:12:45,761 INFO     [sdpa_with_kv_cache.py:26] Loading custom ops library: /Users/myuan/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/extension/llm/custom_ops/libcustom_ops_aot_lib.dylib
[program.cpp:134] InternalConsistency verification requested but not available
[method_meta.cpp:172] Tag: 5 output: 0 is not Tensor
[pybindings.cpp:761] Tensor meta doesn't exist for output 0, error is 0x12, skipping allocating storage
2024-09-02:18:12:52,488 WARNING  [task.py:763] [Task: wikitext] metric word_perplexity is defined, but aggregation is not. using default aggregation=weighted_perplexity
2024-09-02:18:12:52,488 WARNING  [task.py:775] [Task: wikitext] metric word_perplexity is defined, but higher_is_better is not. using default higher_is_better=False
2024-09-02:18:12:52,488 WARNING  [task.py:763] [Task: wikitext] metric byte_perplexity is defined, but aggregation is not. using default aggregation=weighted_perplexity
2024-09-02:18:12:52,488 WARNING  [task.py:775] [Task: wikitext] metric byte_perplexity is defined, but higher_is_better is not. using default higher_is_better=False
2024-09-02:18:12:52,488 WARNING  [task.py:763] [Task: wikitext] metric bits_per_byte is defined, but aggregation is not. using default aggregation=bits_per_byte
2024-09-02:18:12:52,488 WARNING  [task.py:775] [Task: wikitext] metric bits_per_byte is defined, but higher_is_better is not. using default higher_is_better=False
Repo card metadata block was not found. Setting CardData to empty.
2024-09-02:18:12:53,743 WARNING  [repocard.py:107] Repo card metadata block was not found. Setting CardData to empty.
2024-09-02:18:12:53,846 INFO     [task.py:395] Building contexts for wikitext on rank 0...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 62/62 [00:00<00:00, 843.46it/s]
2024-09-02:18:12:53,921 INFO     [evaluator.py:362] Running loglikelihood_rolling requests
  0%|                                                                                                                                                                                                                                                                                                | 0/62 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/Users/myuan/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/myuan/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/myuan/src/executorch/examples/models/llama2/eval_llama.py", line 31, in <module>
    main()  # pragma: no cover
  File "/Users/myuan/src/executorch/examples/models/llama2/eval_llama.py", line 27, in main
    eval_llama(modelname, args)
  File "/Users/myuan/src/executorch/examples/models/llama2/eval_llama_lib.py", line 211, in eval_llama
    eval_results = evaluate_model(
  File "/Users/myuan/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/Users/myuan/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/examples/models/llama2/evaluate/eager_eval.py", line 117, in evaluate_model
    eval_results = evaluate(
  File "/Users/myuan/miniconda3/envs/executorch/lib/python3.10/site-packages/lm_eval/utils.py", line 288, in _wrapper
    return fn(*args, **kwargs)
  File "/Users/myuan/miniconda3/envs/executorch/lib/python3.10/site-packages/lm_eval/evaluator.py", line 373, in evaluate
    resps = getattr(lm, reqtype)(cloned_reqs)
  File "/Users/myuan/miniconda3/envs/executorch/lib/python3.10/site-packages/lm_eval/models/huggingface.py", line 840, in loglikelihood_rolling
    string_nll = self._loglikelihood_tokens(
  File "/Users/myuan/miniconda3/envs/executorch/lib/python3.10/site-packages/lm_eval/models/huggingface.py", line 1033, in _loglikelihood_tokens
    self._model_call(batched_inps, **call_kwargs), dim=-1
  File "/Users/myuan/src/executorch/examples/models/llama2/eval_llama_lib.py", line 74, in _model_call
    raise ValueError(
ValueError: Dim of logits must be 3 for evaluation. Got 2 here. Add --generate_full_logits in export_llama to generate a pte file with full logits.
```

Reviewed By: helunwencser

Differential Revision: D62113387

Pulled By: iseeyuan