Fix qualcomm backend build failure (#12751)
This fixes the build failure of qualcomm backend due to missing
including \<string\>.

```
[  9%] Building C object backends/xnnpack/third-party/cpuinfo/CMakeFiles/cpuinfo.dir/src/x86/cache/init.c.o
In file included from /home/jiefu/executorch/backends/qualcomm/runtime/backends/QnnOpPackageManager.cpp:8:
/home/jiefu/executorch/backends/qualcomm/runtime/backends/QnnOpPackageManager.h:25:12: error: ‘std::string’ has not been declared
   25 |   bool Add(std::string qnn_op_name);
      |            ^~~
/home/jiefu/executorch/backends/qualcomm/runtime/backends/QnnOpPackageManager.h:27:12: error: ‘std::string’ has not been declared
   27 |   bool Has(std::string qnn_op_name);
      |            ^~~
/home/jiefu/executorch/backends/qualcomm/runtime/backends/QnnOpPackageManager.h:29:14: error: ‘std::string’ has not been declared
   29 |   bool Erase(std::string qnn_op_name);
      |              ^~~
/home/jiefu/executorch/backends/qualcomm/runtime/backends/QnnOpPackageManager.h:34:27: error: ‘string’ is not a member of ‘std’
   34 |   std::unordered_set<std::string> qnn_op_package_path_set_;
      |                           ^~~~~~
/home/jiefu/executorch/backends/qualcomm/runtime/backends/QnnOpPackageManager.h:11:1: note: ‘std::string’ is defined in header ‘<string>’; did you forget to ‘#include <string>’?
   10 | #include <unordered_set>
  +++ |+#include <string>
   11 | 
```

---------

Signed-off-by: Jie Fu <jiefu@tencent.com>
Co-authored-by: Gasoonjia <gasoonjia@meta.com>