Windows schannel fix (#18137)
Fix for windows build failures,

```
Error: fatal: unable to access 'https://git.gitlab.arm.com/artificial-intelligence/ethos-u/ethos-u-core-driver.git/': schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.
```

(cherry picked from commit 0c28e7b0be67b9417cc125b9c16775b15a1bed31)