Update export examples to use the long term APIs (#641)
Summary:
Pull Request resolved: https://github.com/pytorch/executorch/pull/641

Migrating callsites to the new api. Should be just plug and play. One difference is the new apis dont allow disabling the verfiers. This causes a problem is emformer_predict and emformer_transcribe because of the following:

torch._export.verifier.SpecViolationError: Operator torch._ops.aten.split.Tensor is not Aten Canonical

torch._export.verifier.SpecViolationError: Operator torch._ops.aten.unbind.int is not Aten Canonical

Also added typing to a bunch of util functions so that its easier to reason about them.

Reviewed By: guangy10

Differential Revision: D49972005

fbshipit-source-id: 215e1ca7ec932fbc5070a6ef837b0b34ba5edac7