Back out "Back out "[executorch] allow passing dynamic shape information in examples dir"" (#1535)
Summary:

Original commit changeset: 1c86682250bb

Original Phabricator Diff: D52418263

original diff had some indents that broke things and some invalid imports for oss. This should fix those. The oss failures I see on this diff are "ImportError: cannot import name 'SchemaVersion' from 'torch._export.serde.schema'" Which is unrelated to this diff.

Reviewed By: larryliu0820, dbort

Differential Revision: D52543599