revert NXP backend: Enable initial unit tests workflow (#11612)
https://github.com/pytorch/executorch/actions/runs/15618919009/job/43998655145
has been failing on trunk. I believe this PR added it to CI so I would
like to remove it since it I have no idea how to forward fix

ERROR: Could not find a version that satisfies the requirement
neutron_converter_SDK_25_03 (from versions: none)
ERROR: No matching distribution found for neutron_converter_SDK_25_03