Qualcomm AI Engine Direct - Fix fp16 unit test (#22059)
### Summary

Since nn.Module has no graph, the fp16 unit test failed with error
"AttributeError: object has no attribute 'graph'".
#21729 introduce the error. Per internal discussion, we don't want to
extend the function to include everything.
Considering the pass already ensure the hadamard transform op exist, we
will revert the change to add expected_target.

### Test plan
```
pytest backends/qualcomm/tests/rework/htp/op/v68/test.py
```