Revert "Remove c10 shim includes and redundant std type aliases" (#21050)
Reverts pytorch/executorch#20900

This causes many internal build failures in internal code like:

```
error: 'using executorch::aten::string_view = class std::basic_string_view<char>' is deprecated [-Werror=deprecated-declarations]
   82 |       ET_UNUSED std::string_view key) const override {
```