Turn exception code off for quantized kernel generated libs (#14962)
Summary:

Explicitly turning exception generated code off for quantized kernels as executorch does not use exceptions in general, and it can cause downstream errors. Detailed error is P1986979595 but the relevant part is:
```
buck-out/ABC/gen/fbsource/6e53edb0a9a0d828/xplat/executorch/kernels/quantized/__generated_lib_combined__/out/RegisterCodegenUnboxedKernelsEverything.cpp:77:44: error: exception handling disabled, use '-fexceptions' to enable
   77 |             } catch (const std::exception& ex) {
      |
```
This means the generated code uses exceptions in its code, so we should explicitly turn them off.

Differential Revision: D84284541