Fix circular dep in flat tensor import (#15902)
Seeing error when important flat tensor deserializer
```
(executorch) [lfq@devvm311.ldc0 /data/users/lfq/executorch (aff5086f)]$ python debug-lora.py 
Traceback (most recent call last):
  File "/data/users/lfq/executorch/debug-lora.py", line 1, in <module>
    from executorch.extension.flat_tensor.serialize.serialize import _deserialize_to_flat_tensor
  File "/data/users/lfq/executorch/src/executorch/extension/flat_tensor/serialize/serialize.py", line 20, in <module>
    from executorch.exir._serialize._cord import Cord
  File "/data/users/lfq/executorch/src/executorch/exir/__init__.py", line 9, in <module>
    from executorch.exir.capture import (
  File "/data/users/lfq/executorch/src/executorch/exir/capture/__init__.py", line 9, in <module>
    from executorch.exir.capture._capture import (
  File "/data/users/lfq/executorch/src/executorch/exir/capture/_capture.py", line 17, in <module>
    from executorch.exir.program import ExirExportedProgram
  File "/data/users/lfq/executorch/src/executorch/exir/program/__init__.py", line 10, in <module>
    from executorch.exir.program._program import (
  File "/data/users/lfq/executorch/src/executorch/exir/program/_program.py", line 82, in <module>
    from executorch.extension.flat_tensor.serialize.serialize import FlatTensorSerializer
ImportError: cannot import name 'FlatTensorSerializer' from partially initialized module 'executorch.extension.flat_tensor.serialize.serialize' (most likely due to a circular import) (/data/users/lfq/executorch/src/executorch/extension/flat_tensor/serialize/serialize.py)
```
Previously, the import happened at module load time, causing the
circular dependency. Now, the import happens at runtime, and we do not
hit the circular dep.