Revert D63918659
Summary:
This diff reverts D63918659
Depends on D64075419
This is breaking the OSS `unittest / linux / linux-job` build:

https://github.com/pytorch/executorch/actions/runs/11242482373/job/31256276319
```
/pytorch/executorch/backends/vulkan/runtime/graph/ops/impl/Staging.cpp:83:26: error: no member named 'starts_with' in 'std::basic_string<char>'
  if (shader.kernel_name.starts_with("bitw8_image_to_nchw_nobitw8buffer")) {
      ~~~~~~~~~~~~~~~~~~ ^
1 error generated.
gmake[2]: *** [backends/vulkan/CMakeFiles/vulkan_backend.dir/build.make:636: backends/vulkan/CMakeFiles/vulkan_backend.dir/runtime/graph/ops/impl/Staging.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
```

Reviewed By: dbort

Differential Revision: D64075435