Update prelude commit
Summary:
To fix an issue on buck2 oss build:

```
(base) [ (eef10728) | larryliu-mp ~/CLionProjects/executorch] buck2 targets //runtime/executor/...
Error parsing root//runtime/executor
From `load` at implicit location

Caused by:
    0: From `load` at third-party/prelude/prelude.bzl:8:6-29
    1: From `load` at third-party/prelude/native.bzl:28:6-18
    2: Error evaluating module: `prelude//rules.bzl`
    3: Traceback (most recent call last):
         * third-party/prelude/rules.bzl:120, in <module>
             rules = {rule.name: _mk_rule(rule) for rule in _declared_rules.values()}
         * third-party/prelude/rules.bzl:78, in _mk_rule
             return rule(
       error: Rules should not declare an attribute named metadata`
         --> third-party/prelude/rules.bzl:78:12
          |
       78 |       return rule(
          |  ____________^
       79 | |         impl = impl,
       80 | |         attrs = attributes,
       81 | |         is_configuration_rule = name in _config_implemented_rules,
       82 | |         is_toolchain_rule = name in toolchain_rule_names,
       83 | |         **extra_args
       84 | |     )
          | |_____^
          |

Failed to parse 1 package
Build ID: 1fe0ed35-ff79-42c3-9586-2947b83e37fc
Jobs completed: 4. Time elapsed: 0.0s.
```

Reviewed By: cccclai

Differential Revision: D47695394

fbshipit-source-id: d1e3e8358cb2cfa201318fc26a940f1c4bf58099