Arm backend: Fix nummerical accuracy error.
A missing .graph caused numerical errors to show up as
"AttributeError: 'GraphModule' object has no attribute 'output_node'"

Signed-off-by: Adrian Lundell <adrian.lundell@arm.com>
Change-Id: Id2f638d506f8dae73b3410bf5903c127a6a891a1