ExecutorchRuntimeException: Update the exception return type (#14483)
Summary:
Fix the JNI layer at the time of throwing the exception. Change the
return type from 'ExecutorchRuntimeException' to 'RuntimeException'

Also disable readLogBuffer from exception flow , A follow up change will
address this. This way it keeps this change to a minimum and unblocks
few Teams for now

Differential Revision: D82995994